name: dotnet unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies Chap 1
        run: dotnet restore Chap-1-ArraysAndStrings.UnitTests/ 
      - name: Build_Chap1
        run: dotnet build Chap-1-ArraysAndStrings.UnitTests/ --configuration Release --no-restore
      - name: Test_Chap1
        run: dotnet test Chap-1-ArraysAndStrings.UnitTests/ --no-restore --verbosity normal  
      - name: Install dependencies Chap 2
        run: dotnet restore Chap-2-LinkedList.UnitTests/ 
      - name: Build_Chap2
        run: dotnet build Chap-2-LinkedList.UnitTests/ --configuration Release --no-restore
      - name: Test_Chap2
        run: dotnet test Chap-2-LinkedList.UnitTests/ --no-restore --verbosity normal  